version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_buscador
    restart: always
    environment:
      POSTGRES_DB: buscador
      POSTGRES_USER: cristobal
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend_buscador_datos
    container_name: backend_buscador
    ports:
      - "8001:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: cristobal
      DB_PASSWORD: 1234
      DB_NAME: buscador
      JWT_SECRET: miclavesecreta
      PORT: 8000
    volumes:
      - ./backend_buscador_datos:/app
    depends_on:
      - postgres
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend_buscador
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge